### PR TITLE
osx-arm64 manual migration

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Hi @conda-forge/help-osx-arm64 @steffengraber this is now (finally) ready for review.

I did a bit of a cleanup as well.

**Comment by Tobias-Fischer** [comment]
Kind reminder @conda-forge/help-osx-arm64 @steffengraber

**Comment by erykoff** [comment]
Looks fine to me but I don’t have any special review powers.

**Comment by Tobias-Fischer** [comment]
Sorry to ping @conda-forge/core but I haven't heard from the osx-arm64 team. Would be great if you could have a look / merge.

Thanks!

**Review by steffengraber — APPROVED** [review]
Just back from holiday, I noticed this fantastic development. Thank you very much for your great help.
Everything looks great. :+1:

**Pull request merged**
